"""add_desktop_activity_logs_table

Revision ID: 07be88f71202
Revises: 
Create Date: 2026-01-15 12:43:50.095659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07be88f71202'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('is_idle', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_domain', 'activity_logs', ['domain'], unique=False)
    op.create_index(op.f('ix_activity_logs_domain'), 'activity_logs', ['domain'], unique=False)
    op.create_index(op.f('ix_activity_logs_start_time'), 'activity_logs', ['start_time'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index('ix_activity_user_time', 'activity_logs', ['user_id', 'start_time'], unique=False)
    op.create_table('desktop_activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('window_title', sa.Text(), nullable=True),
    sa.Column('mouse_count', sa.Integer(), nullable=False),
    sa.Column('key_count', sa.Integer(), nullable=False),
    sa.Column('is_idle', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_desktop_activity_app', 'desktop_activity_logs', ['app_name'], unique=False)
    op.create_index(op.f('ix_desktop_activity_logs_app_name'), 'desktop_activity_logs', ['app_name'], unique=False)
    op.create_index(op.f('ix_desktop_activity_logs_session_id'), 'desktop_activity_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_desktop_activity_logs_timestamp'), 'desktop_activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_desktop_activity_logs_user_id'), 'desktop_activity_logs', ['user_id'], unique=False)
    op.create_index('ix_desktop_activity_session', 'desktop_activity_logs', ['session_id'], unique=False)
    op.create_index('ix_desktop_activity_user_time', 'desktop_activity_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('domain_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_pattern', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_rules_domain_pattern'), 'domain_rules', ['domain_pattern'], unique=False)
    op.create_table('heartbeats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_domain', sa.String(length=255), nullable=True),
    sa.Column('current_title', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_timestamp'), 'heartbeats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_heartbeats_user_id'), 'heartbeats', ['user_id'], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_active_seconds', sa.Integer(), nullable=False),
    sa.Column('total_idle_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sessions_user_id'), 'work_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_sessions_user_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index(op.f('ix_heartbeats_user_id'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_timestamp'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_domain_rules_domain_pattern'), table_name='domain_rules')
    op.drop_table('domain_rules')
    op.drop_index('ix_desktop_activity_user_time', table_name='desktop_activity_logs')
    op.drop_index('ix_desktop_activity_session', table_name='desktop_activity_logs')
    op.drop_index(op.f('ix_desktop_activity_logs_user_id'), table_name='desktop_activity_logs')
    op.drop_index(op.f('ix_desktop_activity_logs_timestamp'), table_name='desktop_activity_logs')
    op.drop_index(op.f('ix_desktop_activity_logs_session_id'), table_name='desktop_activity_logs')
    op.drop_index(op.f('ix_desktop_activity_logs_app_name'), table_name='desktop_activity_logs')
    op.drop_index('ix_desktop_activity_app', table_name='desktop_activity_logs')
    op.drop_table('desktop_activity_logs')
    op.drop_index('ix_activity_user_time', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_start_time'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_domain'), table_name='activity_logs')
    op.drop_index('ix_activity_domain', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('categories')
    # ### end Alembic commands ###
